version: "3"

services:
  
  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: rootpw

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: rootpw
  #     ME_CONFIG_MONGODB_URL: mongodb://root:rootpw@mongo:27017/

  redis:
    image: redis
  redis_commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
      - PORT=8081
    depends_on:
      - redis
  rest_api:
    build: .
    command: /start-reload.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    depends_on:
      - redis