from pydantic import BaseModel
from typing import Optional
import json

class Ticket(BaseModel):
    ticket_id: Optional[str] = None # this will be automatically generated by the create_ticket 
                                    # and create_many_tickets function
    name: str
    from_city: str
    to_city: str
    gate: int
    price: float
    date: str
    file: Optional[bytes] = b''